### ISSUE TITLE
AttributeError with guppy.heapy.UniSet.IdentitySetMulti.partition

### ISSUE THREAD

**Issue by ruomingp** [zhuyifei1999/guppy3#39] opened 2022-01-23 03:11 UTC
Hi 

When trying to print heap, I got an AttributeError. I tweaked the code a bit in UniSet.py to report the types of self and a as well as b:

  File "/home/r_pang_apple_com/.local/lib/python3.8/site-packages/guppy/heapy/UniSet.py", line 336, in __getitem__
    def __getitem__(self, idx): return self.fam.c_getitem(self, idx)
  File "/home/r_pang_apple_com/.local/lib/python3.8/site-packages/guppy/heapy/UniSet.py", line 1613, in c_getitem
    return a.partition.get_set(idx)
  File "/home/r_pang_apple_com/.local/lib/python3.8/site-packages/guppy/heapy/UniSet.py", line 74, in __getattr__
    return self.fam.mod.View.enter(lambda: self.fam.c_getattr(self, other))
  File "/home/r_pang_apple_com/.local/lib/python3.8/site-packages/guppy/heapy/View.py", line 256, in enter
    retval = func()
  File "/home/r_pang_apple_com/.local/lib/python3.8/site-packages/guppy/heapy/UniSet.py", line 74, in <lambda>
    return self.fam.mod.View.enter(lambda: self.fam.c_getattr(self, other))
  File "/home/r_pang_apple_com/.local/lib/python3.8/site-packages/guppy/heapy/UniSet.py", line 800, in c_getattr
    return self.c_getattr2(a, b)
  File "/home/r_pang_apple_com/.local/lib/python3.8/site-packages/guppy/heapy/UniSet.py", line 803, in c_getattr2
    raise AttributeError(f"{type(self)}.{type(a)}.{b}")
AttributeError: <class 'guppy.heapy.UniSet.IdentitySetFamily'>.<class 'guppy.heapy.UniSet.IdentitySetMulti'>.partition

Is this expected?

Thanks.

**Comment by zhuyifei1999** [comment] 2022-01-23 04:25
No that's not expected. Could you check if that's #35 and see if 4e986dece314116f28fdad5b37c68570513655fd workarounds that?

If so, what's it AttributeError-ing on? If not, how do I reproduce this?

**Comment by zhuyifei1999** [comment] 2022-01-23 07:41
Ah, I see in your linked commit the project is about JAX, then yeah this is #35.

**Comment by zhuyifei1999** [comment] 2022-01-27 08:19
Closing as duplicate of #35

**Closed by zhuyifei1999** 2022-01-27 08:19 UTC
