### ISSUE TITLE
python.exe crashed on hpy.heap() after Import Official Dropbox SDK for Python

### ISSUE THREAD

**Issue by viper7882** [zhuyifei1999/guppy3#32] opened 2021-06-25 15:42 UTC
Hi @zhuyifei1999, 

Happened in Windows OS.

Installed Official Dropbox SDK from https://pypi.org/project/dropbox/.
`pip install dropbox`

Ran Python Interpreter
`python`

Python 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.

```
import dropbox
import guppy
hp = guppy.hpy()
before = hp.heap()

```

Windows thrown out exception:

```
Python has stopped working.
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	python.exe
  Application Version:	3.8.10150.1013
  Application Timestamp:	60a5556d
  Fault Module Name:	python38.dll
  Fault Module Version:	3.8.10150.1013
  Fault Module Timestamp:	60a55542
  Exception Code:	c0000005
  Exception Offset:	000000000006dc5b
  Locale ID:	17417
  Additional Information 1:	b59d
  Additional Information 2:	b59df1129b1415b7f11d657440546bce
  Additional Information 3:	53eb
  Additional Information 4:	53eb508f924550baeb8a6a8bb1af95dd

```
If skip importing Dropbox SDK or hpy().heap(), there is no issue.

It is a showstopper issue to me as I'm looking forward for both dropbox and guppy module to work together.

**Comment by zhuyifei1999** [comment] 2021-06-25 16:47
Can't reproduce on Linux:
```
$ pip install guppy3 dropbox
Collecting guppy3
  Using cached guppy3-3.1.0-cp38-cp38-manylinux2010_x86_64.whl (648 kB)
Collecting dropbox
  Using cached dropbox-11.12.0-py3-none-any.whl (571 kB)
Collecting requests>=2.16.2
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting stone>=2.*
  Using cached stone-3.2.1-py3-none-any.whl (160 kB)
Collecting six>=1.12.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting ply>=3.4
  Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
Installing collected packages: urllib3, six, ply, idna, chardet, certifi, stone, requests, guppy3, dropbox
Successfully installed certifi-2021.5.30 chardet-4.0.0 dropbox-11.12.0 guppy3-3.1.0 idna-2.10 ply-3.11 requests-2.25.1 six-1.16.0 stone-3.2.1 urllib3-1.26.6
$ python
Python 3.8.10 (default, Jun  3 2021, 06:01:23) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dropbox
>>> import guppy
>>> hp = guppy.hpy()
>>> before = hp.heap()
>>> before
Partition of a set of 241620 objects. Total size = 28569662 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0  62945  26  7198654  25   7198654  25 str
     1  42014  17  2999568  10  10198222  36 tuple
     2  15988   7  2823770  10  13021992  46 types.CodeType
     3   2999   1  2813552  10  15835544  55 type
     4  15561   6  2116296   7  17951840  63 function
     5   2999   1  2041344   7  19993184  70 dict of type
     6  32029  13  1846650   6  21839834  76 bytes
     7   2004   1  1784064   6  23623898  83 dict (no owner)
     8  27433  11   786864   3  24410762  85 int
     9    331   0   652320   2  25063082  88 dict of module
<798 more rows. Type e.g. '_.more' to view.>
```

There was issue #25. Could you check whether you have pywin32 imported when importing dropbox, and if so, if it is version < 300?

**Comment by zhuyifei1999** [comment] 2021-06-27 02:13
Indeed:

This is a default Anaconda install, then installed dropbox and guppy3:
```
(base) C:\Users\zhuyifei1999>python
Python 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> 'pythoncom' in sys.modules
False
>>> import dropbox
>>> 'pythoncom' in sys.modules
True
>>> import pkg_resources
>>> pkg_resources.get_distribution('pywin32').version
'227'
```

Closing as duplicate of #25

**Closed by zhuyifei1999** 2021-06-27 02:13 UTC
